version: "1"

vars:


default:
  #password-file: "${VW_PASSWORD_FILE}"

  backup:
    verbose: true
    source:
      - "/vaultwarden/data/"
      - "/var/backups/vaultwarden/"
    exclude:
      - "*.tmp"

  run-before:
    - "curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${HC_PING_KEY}/vaultwarden/start"
    - "mkdir -p -m 700 /var/backups/vaultwarden"
    - "sqlite3 /vaultwarden/data/db.sqlite3 \".backup '/var/backups/vaultwarden/vaultwarden.sqlite3'\""

  run-after-success:
    - "find /var/backups/vaultwarden -type f -name 'vaultwarden-*.sqlite' -mtime +14 -delete"
    - "curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${HC_PING_KEY}/vaultwarden"

  run-after-fail:
    - "curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${HC_PING_KEY}/vaultwarden/fail"

  retention:
    after-backup: true
    keep-within: 180d

  check:
    read-data-subset: "100%"

  #schedule: "0 15 3 * * *"

# -------------------------------
# PRIMARY S3
# -------------------------------
vw-s3-primary:
  inherits: "default"
  repository: "/tmp/restic-repo-1"
  env:
    RESTIC_PASSWORD: "password"

vw-s3-secondary:
  inherits: "default"
  repository: "/tmp/restic-repo-2"
  env:
    RESTIC_PASSWORD: "password"

groups:
  vaultwarden-all:
    - "vw-s3-primary"
    - "vw-s3-secondary"
